name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]


    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r app/requirements.txt
      - name: Run tests
        run: |
        cd app
        coverage run manage.py test
      - name: Tests report
        run: coverage report
      - name: Clean coverage
        run: rm ./.coverage